version: "3.9"

services:
  mongo:
    image: mongo
    container_name: hospital-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: mayanksh786/hospital-backend
    container_name: hospital-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    image: mayanksh786/hospital-frontend
    container_name: hospital-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data: